import type { Metadata } from "next"
import { Inter } from "next/font/google"

// eslint-disable-next-line no-restricted-imports
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: {
    default: "for paje that not have a title",
    template: "%s | MyProjects",
  },
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <p className="text-3xl font-bold underline">Header</p>
        </header>
        {children}
        <footer>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  )
}
